In [1]:
import os
import pandas as pd
import numpy as np
import glob

In [2]:
files = glob.glob('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/uni_scale/*.csv')

In [3]:
df = pd.concat([pd.read_csv(f).assign(source=f) for f in files], ignore_index=True)

In [4]:
df.head()

,id,sequence,set,validation,uni_scale,source
0,2TB_000001,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0,/home/lherrmann/projects/enzyme-design/flip2_P...
1,2TB_000002,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0,/home/lherrmann/projects/enzyme-design/flip2_P...
2,2TB_000003,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0,/home/lherrmann/projects/enzyme-design/flip2_P...
3,2TB_000004,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0,/home/lherrmann/projects/enzyme-design/flip2_P...
4,2TB_000005,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0,/home/lherrmann/projects/enzyme-design/flip2_P...

In [5]:
print(df.dtypes)

id                str
sequence          str
set               str
validation       bool
uni_scale     float64
source            str
dtype: object

In [6]:
df_noSource = df.drop('source', axis =1)
df_noSource.head()

,id,sequence,set,validation,uni_scale
0,2TB_000001,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0
1,2TB_000002,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0
2,2TB_000003,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0
3,2TB_000004,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0
4,2TB_000005,MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLR...,test,False,0.0

In [7]:
df_family = df_noSource[df_noSource['id'].str[1:3] == 'TB']

In [8]:
df_family['id'].str[1:3].count()

np.int64(684894)

In [9]:
df_train = df_family[df_family['set']=='train']

In [10]:
df_train.head()
df_train['set'].count()

np.int64(50617)

In [11]:
df_test = df_noSource[df_noSource['set']=='test']

In [12]:
df_test.head()
df_test['set'].count()

np.int64(634277)

In [13]:
# df_noSource.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/pickel/merged_df_for_pickel.csv', index=False)

In [14]:
df_train.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/train_df/TB_family_merged_train.csv', index= False)

In [15]:
df_test.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/test_df/TB_family_merged_test.csv', index=False)