In [ ]:
import os
import pandas as pd
import numpy as np
import glob

In [ ]:
files = glob.glob('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/uni_scale/*.csv')

In [ ]:
df = pd.concat([pd.read_csv(f).assign(source=f) for f in files], ignore_index=True)

In [ ]:
# df = pd.read_csv(all_files)
df.head()

,id,sequence,set,validation,uni_scale,source
0,3AA_000001,LTAPSIKSGVILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.077872,/home/lherrmann/projects/enzyme-design/flip2_P...
1,3AA_000002,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.673774,/home/lherrmann/projects/enzyme-design/flip2_P...
2,3AA_000003,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,train,False,0.126661,/home/lherrmann/projects/enzyme-design/flip2_P...
3,3AA_000004,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.159772,/home/lherrmann/projects/enzyme-design/flip2_P...
4,3AA_000005,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.091523,/home/lherrmann/projects/enzyme-design/flip2_P...

In [ ]:
print(df.dtypes)

id                str
sequence          str
set               str
validation       bool
uni_scale     float64
source            str
dtype: object

In [ ]:
df_noSource = df.drop('source', axis =1)
df_noSource.head()

,id,sequence,set,validation,uni_scale
0,3AA_000001,LTAPSIKSGVILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.077872
1,3AA_000002,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.673774
2,3AA_000003,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,train,False,0.126661
3,3AA_000004,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.159772
4,3AA_000005,LTAPSIKSGTILHAWNWSFNTLKHNMKDIHDAGYTAIQTSPINQVK...,test,False,0.091523

In [ ]:
df_train = df_noSource[df_noSource['set']=='train']

In [ ]:
df_train.head()
df_train['set'].count()

np.int64(72408)

In [ ]:
df_test = df_noSource[df_noSource['set']=='test']

In [ ]:
df_test.head()
df_test['set'].count()

np.int64(691655)

In [ ]:
df_noSource.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/pickel/merged_df_for_pickel.csv', index=False)

In [ ]:
df_train.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/train_df/df_merged_train.csv', index= False)

In [ ]:
df_test.to_csv('/home/lherrmann/projects/enzyme-design/flip2_Project/test/csv_id/test_df/df_test.csv', index=False)